### PR TITLE
Upload imported skybox materials

### PR DESCRIPTION
**Pull request by kristiker**
Imported all the skyboxes with my updated source2utils fork

Let me know if it works and if they need any tweaking (looked quite a bit dim from what I saw)

image

### CODE REVIEW

**Comment by 5FB5** [comment]
Ok, I'll check your update now and let you know

**Comment by 5FB5** [comment]
I see that you changed "urban_horizon", but it works as non-skybox material. Is this the way it should be?
image

**Comment by 5FB5** [comment]
So, I compared your update and the version from the Valve's converter, it looks better and works the way I need. I can add your version, but I think you still need to work on this
image
image

**Comment by kristiker** [comment]
Yes, I'm sure this is how it is on source1. It's not a proper 'skybox' material.

**Comment by 5FB5** [comment]
All models, materials and particles are imported via Valve's tool and presented in this repository, but it works not like you think. Some assets are broken - some models can't be shown or just can crash the game, some materials are broken like blend textures, majority of particles are broken (also because s&box has updated tools) and e.t.c. Also old vmf map format can be imported to S2's Hammer, but you can't compile in release quality, because BSP brushes are broken (S2 has a mesh system now), most of the lighting will be broken. It can be different from game to game (check TF: Source 2 team and you can see more successful results than my)

**Comment by 5FB5** [comment]
I've received your request. I will check it in the morning :)

**Comment by 5FB5** [comment]
Well, I don't see any changes. I believe they are there, but the final image is not particularly affected. The changes are especially noticeable in the editor. Correct skybox is very bright, and also environment light from it is superimposed more correctly
Screenshot_4
Screenshot_5

**Comment by kristiker** [comment]
OK, apparently the preview material window is way different from actual in-game result. I checked in-game and it is indeed still dim.

I'm more interested in porting the material as close to 1:1 with the original as possible, and I understand that what you have is a better fit for the map.

I was able to get the sky looking pretty close to original and to the manually imported .exr by changing Render Only Exposure Bias form 1.0 to 2.5 on the material. take a look
<details>
  <summary>Original - <code>sky_l4d_c1_1_hdr</code></summary>
  <image src="https://user-images.githubusercontent.com/26466974/130227419-2a1efd76-4686-43bf-8c13-301449de2e26.png">
</details>
<details>
  <summary>Manual port by Justyn - <code>sky_l4d_c1_1_hdr.exr</code></summary>
  <image src="https://user-images.githubusercontent.com/26466974/130227539-e35d1380-f051-4c5a-9223-07d90df4c6d0.png">
</details>
<details>
  <summary>My port with + material param fix - <code>sky_l4d_c1_1_hdr_cube.pfm</code></summary>
  <image src="https://user-images.githubusercontent.com/26466974/130227573-767906d0-1ad0-4e8d-ab70-8d5504bf3274.png">
</details>

  

And `sky_l4d_predawn02_hdr` here https://imgsli.com/NjY3ODM

**Comment by 5FB5** [comment]
Hello again! Can you update skyboxes with blended horizon please? Very painful to work 
image
image

**Comment by kristiker** [comment]
The thing is you are supposed to cover that area with fog and 3d skybox. But I can do it, shouldn't be that hard nevertheless.
image
image

**Comment by 5FB5** [comment]
Ok, I'll try to fix it by myself

**Pull request merged**
